name: keep_code
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  dio: ^5.1.1
  get_it: ^7.2.0
  json_annotation: ^4.8.0
  retrofit: ^4.0.1
  connectivity_plus:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
